version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: staging
    labels:
      - dependencies
      - python
    groups:
      python-dependencies:
        dependency-type: production
        update-types:
          - patch
          - minor

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: staging
    labels:
      - dependencies
      - rust
    groups:
      rust-dependencies:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    target-branch: staging
    labels:
      - dependencies
      - ci
