#!/usr/bin/env python3
"""
agents_md_gen.py — two-stage AGENTS.md stitcher.

Stage 1 (static): constitution preamble from agentic-dev-constitution skill.
Stage 2 (model):  repo deep-scan body — produced by a subagent/Hermes, passed via --body.
Stitches preamble + body and writes AGENTS.md (skips if exists unless --force).

Usage:
  agents_md_gen.py <repo_path> --body <file|'-'> [--force]
  cat body.md | agents_md_gen.py /path/to/repo --body -
"""
import sys
from pathlib import Path

PREAMBLE = """# AGENTS.md

> Generated by `agents_md_gen.py` (global rules + repository truth).
> Any AI agent (Hermes / Codex / opencode / Kilo) working here MUST follow this. No guessing.

## Global Constitution (applies to all configured repositories)
- **TypeScript (web)** → Bun. Next.js/React dominant. Do NOT rewrite web in Rust+WASM.
- **Python** → uv preferred; BUT use the repo's actual PM if it's Poetry/conda. pip banned for new agents.
- **Rust** → cargo. Aspirational default for CLI/systems where crates exist. Else `# TODO(rust-migration)`.
- **C# / Unity** → NuGet/UPM. Locked, no migration.
- **Solidity** → Foundry/forge or Hardhat. NOT a web app — never `bun dev`.
- **Every repo** gets this AGENTS.md. Unity trap: `Assets/package.json` = npm-in-Unity bridges, not app TS.

---
"""

def main():
    args = sys.argv[1:]
    force = "--force" in args
    args = [a for a in args if a != "--force"]
    body = None
    if "--body" in args:
        i = args.index("--body")
        body_src = args[i + 1]
        args = args[:i] + args[i + 2:]
        if body_src == "-":
            body = sys.stdin.read()
        else:
            body = Path(body_src).read_text()
    if not args:
        print("usage: agents_md_gen.py <repo_path> --body <file|'-'> [--force]", file=sys.stderr)
        sys.exit(1)
    repo = Path(args[0]).resolve()
    if not repo.is_dir():
        print(f"ERROR: {repo} not a dir", file=sys.stderr)
        sys.exit(1)
    if body is None:
        print("ERROR: --body required", file=sys.stderr)
        sys.exit(1)
    out = repo / "AGENTS.md"
    if out.exists() and not force:
        print(f"SKIP (exists): {out}  [--force to overwrite]")
        sys.exit(0)
    content = PREAMBLE + "\n" + body.strip() + "\n"
    out.write_text(content)
    print(f"WROTE: {out}  ({len(content)} bytes)")

if __name__ == "__main__":
    main()
