#!/usr/bin/env python3
"""
repo_standardize.py — repository stack enforcer.

Walks a repo, detects its primary language(s), and drops a correct AGENTS.md
so any agent (Hermes, Codex, opencode, Kilo) knows the toolchain WITHOUT guessing.

Constitution (locked):
  - TypeScript  -> Bun     (Next.js/React for web; npm only inside Unity Assets)
  - Python      -> uv      (pip is banned for agentic flows)
  - Rust        -> cargo   (aspirational default for CLI/systems/tools)
  - C# / Unity  -> NuGet   (locked, no choice)
  - Web stays TS. Do NOT rewrite web in Rust+WASM unless perf hotpath.

Usage:
  repo_standardize.py [path]            # detect + write AGENTS.md
  repo_standardize.py --check [path]    # print what WOULD be written, don't write
  repo_standardize.py --force [path]    # overwrite existing AGENTS.md

Exit 0 = wrote/confirmed, 1 = bad args.
"""

import sys
from pathlib import Path

# ---- detection ----------------------------------------------------------
from stack_detect import detect_signals, primary_lang


# ---- AGENTS.md templates ------------------------------------------------
def agents_md(lang: str, sig: dict, repo_name: str) -> str:
    header = f"""# AGENTS.md — {repo_name}

> Auto-generated by `repo_standardize.py`.
> Any AI agent working in this repo MUST follow the commands below. No guessing.

"""
    if lang == "solidity":
        tool = "Foundry (forge)" if sig.get("sol_tool") == "foundry.toml" else "Hardhat"
        return (
            header
            + f"""## Stack
- **Language:** Solidity (smart contracts)
- **Toolchain:** {tool}
- **Why:** Blockchain contracts. NOT a web app — do NOT treat package.json as a Bun web project.

## Commands
- Foundry:    `forge build` / `forge test` / `forge fmt`
- Hardhat:    `bun hardhat compile` / `bun hardhat test` (bun is the script runner, Solidity is the product)
- Deploy:     see `scripts/` or `deploy/` in repo

## Conventions
- `package.json` here drives Hardhat/Foundry, not a Next.js app. Agents: run contract commands, not `bun dev`.
- Never mix this with the web TS monorepo toolchain.
- Audit critical: `slither` or `forge inspect` before mainnet deploys.
"""
        )
    elif lang == "rust":
        return (
            header
            + """## Stack
- **Language:** Rust
- **Package manager:** cargo (rustup-managed, stable-aarch64-apple-darwin)
- **Why:** Systems / CLI / perf-critical. This is the aspirational default for new tooling.

## Commands
- Build:      `cargo build`
- Release:    `cargo build --release`
- Test:       `cargo test`
- Lint:       `cargo clippy --all-targets -- -D warnings`
- Format:     `cargo fmt`
- Audit deps: `cargo audit`

## Conventions
- wasm32 target already installed (`rustup target add wasm32-unknown-unknown`) for browser interop.
- NO npm/cargo mix unless explicitly a wasm-bindgen project.
- If a Python CLI could be Rust, prefer Rust. Leave `// TODO(rust-migration)` breadcrumbs otherwise.
"""
        )
    elif lang == "typescript":
        pm = (
            "bun"
            if (sig.get("bun_lock") or not sig.get("npm_lock"))
            else "bun (npm lock present — migrate to bun)"
        )
        return (
            header
            + f"""## Stack
- **Language:** TypeScript (web: Next.js / React)
- **Package manager:** {pm}
- **Why:** Web stays TypeScript. Tooling for Rust+WASM web is not ready; do NOT rewrite web in Rust.

## Commands
- Install:    `bun install`
- Dev:        `bun dev`
- Build:      `bun run build`
- Test:       `bun test`  (or `bun run test`)
- Lint:       `bun run lint`
- Typecheck:  `bun run typecheck` (or `tsc --noEmit`)

## Conventions
- Monorepo? Use workspace root scripts. Never `cd` into packages and run raw `npm`.
- Husky + lint-staged active. Commits run hooks — don't bypass with --no-verify.
- 5-verb repo standard: the repo exposes exactly 5 root scripts.
"""
        )
    elif lang == "python":
        pm = "uv" if sig.get("uv") else "uv (NO pip — migrate lockfile to uv)"
        return (
            header
            + f"""## Stack
- **Language:** Python 3.11+
- **Package manager:** {pm}
- **Why:** Glue, data, automation, ML. Mature for agentic flows.

## Commands
- Sync:       `uv sync`
- Run:        `uv run <module>`
- Test:       `uv run pytest`
- Lint:       `uv run ruff check .`
- Format:     `uv run ruff format .`

## Conventions
- `pyproject.toml` is the single source of truth. No setup.py sprawl.
- If this is a CLI/tool that could be Rust, mark with `# TODO(rust-migration)`.
- venvs live in `.venv`; never commit them.
"""
        )
    elif lang == "unity-cs":
        return (
            header
            + """## Stack
- **Language:** C# (Unity)
- **Package manager:** NuGet / Unity Package Manager
- **Why:** Locked. Unity owns the runtime. No choice, no migration.

## Commands
- Build:      Unity Editor (CI uses Unity CLI / GameCI)
- Test:       Unity Test Runner (EditMode + PlayMode)

## Conventions
- `Assets/package.json` files are npm-in-Unity (jslib bridges) — separate from app TS.
- Do NOT run `bun install` at repo root expecting app behavior — those are Unity asset packages.
- Never let an agent treat the Unity project as a Node monorepo.
"""
        )
    elif lang == "mixed-ts-py":
        return (
            header
            + """## Stack
- **Mixed:** TypeScript (web) + Python (glue/automation)
- **Package managers:** Bun (TS) + uv (Python) — NEVER mix pip into the TS side.

## Commands
- TS:   `bun install` / `bun run build` / `bun test`
- Py:   `uv sync` / `uv run pytest` / `uv run ruff check .`

## Conventions
- Keep the two stacks in separate top-level dirs (e.g. `web/` + `scripts/` or `py/`).
- Agents MUST detect which subtree they're in before running commands.
"""
        )
    return (
        header
        + """## Stack
- **Unknown / unmapped.**

## Action Required
Run `repo_standardize.py` after adding code, or manually declare the stack here.
"""
    )


# ---- main ---------------------------------------------------------------
def main():
    args = sys.argv[1:]
    check_only = "--check" in args
    force = "--force" in args
    paths = [a for a in args if not a.startswith("--")]
    if not paths:
        print("usage: repo_standardize.py [--check|--force] <path>", file=sys.stderr)
        sys.exit(1)
    target = Path(paths[0]).resolve()
    if not target.is_dir():
        print(f"ERROR: {target} is not a directory", file=sys.stderr)
        sys.exit(1)

    sig = detect_signals(target)
    lang = primary_lang(sig)
    repo_name = target.name
    content = agents_md(lang, sig, repo_name)
    out = target / "AGENTS.md"

    print(f"== repo_standardize.py: {target}")
    print(f"   detected: {lang}")
    signals = " ".join(
        f"{k}={sig.get(k, False)}"
        for k in (
            "ts",
            "py",
            "rust",
            "cs",
            "sol",
            "unity",
            "bun_lock",
            "npm_lock",
            "uv",
        )
    )
    print(f"   signals : {signals}")

    if check_only:
        print("\n--- AGENTS.md (dry-run, not written) ---\n")
        print(content)
        return
    if out.exists() and not force:
        print(f"   SKIP: {out} exists (use --force to overwrite)")
        return
    out.write_text(content)
    print(f"   WROTE: {out}")


if __name__ == "__main__":
    main()
